<?php

namespace App\Filament\Resources\CommissionShareResource\Pages;

use App\Filament\Resources\CommissionShareResource;
use Filament\Resources\Pages\ListRecords;

// No CreateAction — rows are generated by GenerateCommissionShare, not created manually.
class ListCommissionShares extends ListRecords
{
    protected static string $resource = CommissionShareResource::class;
}
